// All antd theme variables: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

export default {
  '@blue-base': '#4885ED',
  '@green-base': '#4EBF67',
  '@gold-base': '#FFA94C',
  '@red-base': '#FC604C',
  '@primary-color': '#4885ED',
  '@primary-1': '#F0F8FF',
  '@primary-2': '#F0F7FF',
  '@primary-3': '#C7E1FF',
  '@primary-4': '#9EC8FF',
  '@primary-5': '#73A9FA',
  '@primary-6': '#4885ED',
  '@primary-7': '#3263C7',
  '@primary-8': '#2047A1',
  '@primary-9': '#122E7A',
  '@primary-10': '#0C1D54',
  '@link-color': '#4885ED',
  '@success-color': '#4EBF67',
  '@warning-color': '#FFA94C',
  '@error-color': '#FC604C',
  '@info-color': 'rgba(0, 0, 0, 0.87)',
  '@alert-info-border-color': 'rgba(0, 0, 0, 0.54)',
  '@alert-info-bg-color': '#F5F5F5',
  '@alert-info-icon-color': 'rgba(0, 0, 0, 0.54)',
  '@alert-success-border-color': '@success-color',
  '@alert-success-bg-color': '#F0FFF0',
  '@alert-success-icon-color': '@success-color',
  '@alert-warning-border-color': '@warning-color',
  '@alert-warning-bg-color': '#FFFAF0',
  '@alert-warning-icon-color': '@warning-color',
  '@alert-error-border-color': '@error-color',
  '@alert-error-bg-color': '#FFF4F0',
  '@alert-error-icon-color': '@error-color',
  '@heading-color': 'rgba(0, 0, 0, 0.87)',
  '@text-color': 'rgba(0, 0, 0, 0.87)',
  '@text-color-secondary': 'rgba(0, 0, 0, 0.32)',
  '@disabled-color': 'rgba(0, 0, 0, 0.24)',
  '@border-radius-base': '4px',
  '@card-radius': '6px',
  '@border-color-base': 'rgba(0, 0, 0, 0.12)',
  '@btn-shadow': 'none',
  '@btn-primary-shadow': 'none',
  '@btn-text-shadow': 'none',
  '@table-row-hover-bg': '#F0F8FF',
  '@select-selection-item-border-color': 'rgba(0, 0, 0, 0.12)',
  '@input-addon-bg': '#FFFFFF',
  '@slider-track-background-color': '@primary-4',
  '@slider-track-background-color-hover': '@primary-5',
  '@slider-handle-color': '@primary-4',
  '@slider-handle-color-hover': '@primary-5',
  '@slider-rail-background-color': 'rgba(0, 0, 0, 0.12)',
};
